export const ROUTES = {
  LOGIN: '/login',

  DASHBOARD: '/',

  BLOG_LIST:    '/blog',
  BLOG_NEW:     '/blog/new',
  BLOG_EDIT:    '/blog/:id/edit',
  BLOG_DETAIL:  '/blog/:id',

  CONTENT_CALENDAR_LEGACY: '/calendar',

  CAMPAIGN_LIST:   '/campaigns',
  CAMPAIGN_NEW:    '/campaigns/new',
  CAMPAIGN_EDIT:   '/campaigns/:id/edit',
  CAMPAIGN_DETAIL: '/campaigns/:id',

  LANDING_LIST:   '/landing',
  LANDING_DETAIL: '/landing/:id',

  SOCIAL_PLANNER: '/social',
  SOCIAL_QUEUE:   '/social/queue',

  EMAIL_LIST:    '/email',
  EMAIL_DETAIL:  '/email/:id',

  WHATSAPP_LIST:   '/whatsapp',
  WHATSAPP_DETAIL: '/whatsapp/:id',

  SEO_PLANS:    '/seo/plans',
  KEYWORD_IDEAS:'/seo/keywords',

  CREATIVE_BRIEFS: '/creative-briefs',

  ANALYTICS: '/analytics',

  LEADS:        '/leads',
  ENGAGE_PUSH:  '/leads/engage-push',

  BOT_QUEUE:    '/bot/queue',
  BOT_REPORTS:  '/bot/reports',
  BOT_REPORT_DETAIL: '/bot/reports/:id',

  APPROVALS: '/approvals',

  SETTINGS:    '/admin/settings',
  BOT_SETTINGS:'/admin/bot-mode',
  AUDIT_LOGS:  '/admin/audit-logs',
  API_HEALTH:  '/admin/api-health',
  CONSOLE_SYNC:'/admin/console-sync',
  WORKER_STATUS:'/admin/worker-status',
  JOBS: '/admin/jobs',
  JOB_DETAIL: '/admin/jobs/:id',
  LOCAL_BOT_REPORTS: '/admin/local-bot-reports',
  FORBIDDEN: '/forbidden',

  // Phase 1: Knowledge Foundation
  KNOWLEDGE:            '/knowledge',
  KNOWLEDGE_PRODUCTS:   '/knowledge/products',
  KNOWLEDGE_PRODUCT:    '/knowledge/products/:id',
  KNOWLEDGE_PERSONAS:   '/knowledge/personas',
  KNOWLEDGE_INDUSTRIES: '/knowledge/industries',
  KNOWLEDGE_MARKETS:    '/knowledge/markets',
  KNOWLEDGE_PROBLEMS:   '/knowledge/problems',
  KNOWLEDGE_INTENTS:    '/knowledge/search-intents',
  KNOWLEDGE_CLUSTERS:   '/knowledge/topic-clusters',
  KNOWLEDGE_SOURCES:    '/knowledge/sources',
  KNOWLEDGE_CITATIONS:  '/knowledge/citations',
  KNOWLEDGE_CLAIMS:     '/knowledge/claims',
  KNOWLEDGE_BRAND_RULES:   '/knowledge/brand-rules',
  KNOWLEDGE_POLICIES:      '/knowledge/content-policies',
  KNOWLEDGE_COMPLETENESS:  '/knowledge/completeness',

  // Phase 2: Unified Content Studio
  CONTENT:             '/content',
  CONTENT_NEW:         '/content/new',
  CONTENT_DETAIL:      '/content/:id',
  CONTENT_EDIT:        '/content/:id/edit',
  CONTENT_VERSIONS:    '/content/:id/versions',
  CONTENT_BRIEF:       '/content/:id/brief',
  CONTENT_COMMENTS:    '/content/:id/comments',
  CONTENT_VALIDATIONS: '/content/:id/validations',
  CONTENT_SCHEDULE:    '/content/:id/schedule',
  CONTENT_CALENDAR:    '/content/calendar',
  CONTENT_DAILY_PACK:  '/content/daily-pack',
  CONTENT_TEMPLATES:   '/content/templates',

  // Phase 3: AI Control Centre
  AI:                    '/ai',
  AI_DASHBOARD:          '/ai/dashboard',
  AI_PROVIDERS:          '/ai/providers',
  AI_PROVIDER_DETAIL:    '/ai/providers/:id',
  AI_MODELS:             '/ai/models',
  AI_ROUTING:            '/ai/routing',
  AI_PROMPTS:            '/ai/prompts',
  AI_PROMPT_DETAIL:      '/ai/prompts/:id',
  AI_GENERATIONS:        '/ai/generations',
  AI_GENERATION_DETAIL:  '/ai/generations/:uuid',
  AI_USAGE:              '/ai/usage',
  AI_BUDGETS:            '/ai/budgets',
  AI_VALIDATIONS:        '/ai/validations',
  AI_HEALTH:             '/ai/health',

  // Blog Command Centre
  BLOG_COMMAND_CENTRE: '/blog-command-centre',
  BCC_ROADMAP: '/blog-command-centre/roadmap',
  BCC_ROADMAP_CANDIDATES: '/blog-command-centre/roadmap/candidates',
  BCC_ROADMAP_SCORED: '/blog-command-centre/roadmap/scored',
  BCC_ROADMAP_GAPS: '/blog-command-centre/roadmap/gaps',
  BCC_ROADMAP_REFRESH: '/blog-command-centre/roadmap/refresh',
  BCC_ROADMAP_OPTIMIZER: '/blog-command-centre/roadmap/optimizer',
  BCC_ROADMAP_CLUSTERS: '/blog-command-centre/roadmap/clusters',
  BCC_PIPELINE: '/blog-command-centre/pipeline',
  BCC_PIPELINE_BRIEFS: '/blog-command-centre/pipeline/briefs',
  BCC_PIPELINE_DRAFTS: '/blog-command-centre/pipeline/drafts',
  BCC_PIPELINE_VERSIONS: '/blog-command-centre/pipeline/versions',
  BCC_PIPELINE_EDITORIAL: '/blog-command-centre/pipeline/editorial',
  BCC_PIPELINE_RESEARCH: '/blog-command-centre/pipeline/research',
  BCC_VERIFICATION: '/blog-command-centre/verification',
  BCC_VERIFICATION_CLAIMS: '/blog-command-centre/verification/unsupported-claims',
  BCC_VERIFICATION_SOURCES: '/blog-command-centre/verification/source-review',
  BCC_VERIFICATION_RISK: '/blog-command-centre/verification/risk-review',
  BCC_VERIFICATION_MEDIA: '/blog-command-centre/verification/media',
  BCC_APPROVALS: '/blog-command-centre/approvals',
  BCC_APPROVALS_HISTORY: '/blog-command-centre/approvals/history',
  BCC_PUBLISHING: '/blog-command-centre/publishing',
  BCC_PUBLISHING_READY: '/blog-command-centre/publishing/ready',
  BCC_PUBLISHING_CALENDAR: '/blog-command-centre/publishing/calendar',
  BCC_PUBLISHING_SCHEDULED: '/blog-command-centre/publishing/scheduled',
  BCC_PUBLISHING_DEPLOYMENTS: '/blog-command-centre/publishing/deployments',
  BCC_PUBLISHING_ROLLBACK: '/blog-command-centre/publishing/rollback',
  BCC_PUBLISHING_UNPUBLISH: '/blog-command-centre/publishing/emergency-unpublish',
  BCC_PUBLISHED: '/blog-command-centre/published',
  // 2026-08: the SEO and Indexing section moved out of the Blog Command
  // Centre tab strip and became "Blog SEO and Indexing" under the SEO
  // sidebar block (see BLOG_SEO_* below). These paths stay as redirects so
  // existing bookmarks keep working.
  BCC_SEO: '/blog-command-centre/seo',
  BCC_SEO_SEARCH: '/blog-command-centre/seo/search',
  BCC_SEO_INTERNAL_LINKS: '/blog-command-centre/seo/internal-links',
  BCC_SEO_CANNIBALISATION: '/blog-command-centre/seo/cannibalisation',
  BCC_SEO_SITEMAP: '/blog-command-centre/seo/sitemap',
  BCC_SEO_TECHNICAL: '/blog-command-centre/seo/technical',
  BCC_INDEXING: '/blog-command-centre/indexing',
  BCC_ANALYTICS: '/blog-command-centre/analytics',
  BCC_ANALYTICS_PORTFOLIO: '/blog-command-centre/analytics/portfolio',
  BCC_ANALYTICS_CONTENT: '/blog-command-centre/analytics/content',
  BCC_ANALYTICS_SEARCH: '/blog-command-centre/analytics/search',
  BCC_ANALYTICS_PRODUCT: '/blog-command-centre/analytics/product',
  BCC_ANALYTICS_ATTRIBUTION: '/blog-command-centre/analytics/attribution',
  BCC_OPERATIONS: '/blog-command-centre/operations',
  BCC_OPERATIONS_QUEUE: '/blog-command-centre/operations/queue',
  BCC_OPERATIONS_FAILED: '/blog-command-centre/operations/failed-jobs',
  BCC_OPERATIONS_CRON: '/blog-command-centre/operations/cron',
  BCC_OPERATIONS_AI_USAGE: '/blog-command-centre/operations/ai-usage',
  BCC_OPERATIONS_PROVIDER_HEALTH: '/blog-command-centre/operations/provider-health',
  BCC_OPERATIONS_PROVIDER_ROUTING: '/blog-command-centre/operations/provider-routing',
  BCC_OPERATIONS_AUDIT: '/blog-command-centre/operations/audit',
  BCC_SETTINGS: '/blog-command-centre/settings',
  BCC_SETTINGS_PORTFOLIO: '/blog-command-centre/settings/portfolio',
  BCC_SETTINGS_AUTOMATION_WINDOW: '/blog-command-centre/settings/automation-window',
  BCC_SETTINGS_PUBLICATION_RULES: '/blog-command-centre/settings/publication-rules',
  BCC_SETTINGS_RISK_RULES: '/blog-command-centre/settings/risk-rules',
  BCC_SETTINGS_PROVIDER_ROUTING: '/blog-command-centre/settings/provider-routing',
  BCC_SETTINGS_VERIFICATION_THRESHOLDS: '/blog-command-centre/settings/verification-thresholds',
  BCC_SETTINGS_STORAGE: '/blog-command-centre/settings/storage',
  BCC_SETTINGS_SEO: '/blog-command-centre/settings/seo',
  BCC_SETTINGS_NOTIFICATIONS: '/blog-command-centre/settings/notifications',

  // Blog SEO and Indexing — sidebar SEO block, sibling of the SEO Command
  // Centre. Was the Blog Command Centre's "SEO and Indexing" tab, which
  // deep-linked out to Intelligence and ejected the operator from the BCC
  // chrome; these leaves now render in place under their own sub-nav.
  BLOG_SEO: '/blog-seo',
  BLOG_SEO_SEARCH: '/blog-seo/search-console',
  BLOG_SEO_INDEXING: '/blog-seo/indexing',
  BLOG_SEO_INTERNAL_LINKS: '/blog-seo/internal-links',
  BLOG_SEO_CANNIBALISATION: '/blog-seo/cannibalisation',
  BLOG_SEO_SITEMAP: '/blog-seo/sitemap',
  BLOG_SEO_TECHNICAL: '/blog-seo/technical',
};
