const STATUS_COLOR = {
  draft: 'secondary',
  archived: 'secondary',
  idea: 'secondary',
  active: 'success',
  approved: 'success',
  published: 'success',
  sent: 'success',
  posted: 'success',
  completed: 'success',
  running: 'info',
  scheduled: 'info',
  in_progress: 'info',
  in_review: 'warning',
  seo_review: 'warning',
  internal_review: 'warning',
  pending_approval: 'warning',
  pending_publishing: 'warning',
  pending_push: 'warning',
  pending: 'warning',
  awaiting_approval: 'warning',
  manual_queue: 'warning',
  paused: 'warning',
  retry_scheduled: 'warning',
  failed: 'danger',
  rejected: 'danger',
  duplicate: 'secondary',
  cancelled: 'secondary',
  not_required: 'secondary',
  none: 'secondary',
  queued: 'info',
  sending: 'info',
  open: 'info',
  done: 'success',
  publishing: 'info',
  planned: 'info',
  pushed: 'success',
  ok: 'success',
  error: 'danger',
  ready: 'success',
  misconfigured: 'warning',
  not_configured: 'secondary',
};

export function StatusBadge({ status }) {
  const color = STATUS_COLOR[status] || 'secondary';
  const label = status ? String(status).replace(/_/g, ' ') : 'unknown';
  return <span className={`badge badge-${color}`}>{label}</span>;
}
