<?php

namespace App\Commands;

use App\Libraries\Ai\Images\ImageProviderRegistry;
use App\Libraries\Blog\BlogFeatureFlags;
use App\Libraries\Blog\WorkBlockService;
use App\Libraries\Database\SchemaGuard;
use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;
use Config\Database;
use Throwable;

/**
 * `php spark reach:blog-generate-covers` — queue cover generation for blog
 * items that reached publication without one.
 *
 * A cover comes from the GENERATE_IMAGE work block, which the state machine
 * schedules on the FACT_VERIFIED transition. Items that reached publish_queued
 * without passing through it have no cover and nothing queued to make one, so
 * every publish attempt dies on:
 *
 *   Featured image is not assigned; a suitable cover is required before publication
 *
 * Unlike SEO metadata, a cover cannot be derived from what is already there —
 * it has to be generated, which costs provider spend. So this only ever queues
 * the work; it never generates inline, and it refuses to queue anything when
 * image generation is switched off or unconfigured, because those blocks would
 * fail the moment a worker picked them up.
 *
 * Not the same job as CoverSweepService, which runs on a schedule and re-queues
 * cover work for articles *parked* by a failed cover_image validation, mostly
 * so an uploaded gallery cover gets picked up. This is operator-driven and
 * covers a population that sweep cannot see: items that never acquired a cover
 * at all, and so never got a validation row to fail. Where the two populations
 * overlap, this defers — an item with cover work already in flight is skipped,
 * so the same article is never billed for two images.
 *
 * Dry run by default.
 */
class ReachBlogGenerateCovers extends BaseCommand
{
    use \App\Commands\Concerns\ParsesSparkOptions;

    protected $group       = 'Reach';
    protected $name        = 'reach:blog-generate-covers';
    protected $description = 'Queue cover-image generation for blog items missing a featured image.';
    protected $usage       = 'reach:blog-generate-covers [--apply] [--limit 0]';
    protected $options     = [
        '--apply' => 'Queue the generation work. Without it the command only reports.',
        '--limit' => 'Stop after N items (default: 0 = no limit).',
    ];

    /** States where a cover is expected to exist already. */
    private const PUBLISHABLE_STATES = [
        'approved', 'scheduled', 'ready_for_publication', 'publish_queued', 'publishing',
    ];

    public function run(array $params): int
    {
        // CLI::getOption() only sees real argv; command() passes flags in $params.
        $apply = $this->sparkFlag('apply', $params);
        $limit = max(0, (int) ($this->sparkOption('limit', $params, '0') ?? '0'));

        $db = Database::connect();

        try {
            if (! SchemaGuard::hasTable($db, 'reach_blog_publication_profiles')) {
                CLI::error('reach_blog_publication_profiles does not exist.');

                return EXIT_ERROR;
            }

            $items = $this->itemsMissingCovers($db, $limit);

            if ($items === []) {
                CLI::write('Every blog item past approval already has a cover image.', 'green');

                return EXIT_SUCCESS;
            }

            CLI::write(sprintf(
                '%s %d blog item(s) with no cover image:',
                $apply ? 'Queueing covers for' : 'Found',
                count($items),
            ), $apply ? 'green' : 'yellow');
            CLI::newLine();
            CLI::table(
                array_map(static fn ($i) => [$i['id'], mb_substr($i['title'], 0, 60), $i['workflow_status']], $items),
                ['#', 'title', 'state'],
            );

            // Say what this will cost before it costs anything.
            CLI::newLine();
            CLI::write(sprintf(
                '%d image(s) would be generated by the configured image provider — this is billable provider spend.',
                count($items),
            ), 'yellow');

            $blocked = $this->generationBlockedReason();
            if ($blocked !== null) {
                CLI::newLine();
                CLI::error('Cannot queue cover generation: ' . $blocked);
                CLI::write(
                    'Fix that first, or give these posts covers from the Cover Gallery, or waive the '
                    . 'cover_image validation per post to publish without one.',
                    'yellow',
                );

                return EXIT_ERROR;
            }

            if (! $apply) {
                CLI::newLine();
                CLI::write('Dry run — nothing queued. Re-run with --apply to queue the work.', 'yellow');

                return EXIT_SUCCESS;
            }

            $workBlocks = new WorkBlockService();
            $queued     = [];

            foreach ($items as $item) {
                $blockId = $workBlocks->chainGenerateImage($item['id'], $item['content_version_id']);
                if ($blockId !== null) {
                    $queued[] = [$item['id'], mb_substr($item['title'], 0, 50), $blockId];
                }
            }

            CLI::newLine();
            CLI::write(sprintf('Queued %d cover-generation block(s).', count($queued)), 'green');
            CLI::table($queued, ['item', 'title', 'work block']);

            CLI::newLine();
            CLI::write('Nothing has been generated yet — run a worker to execute the blocks:', 'green');
            CLI::write('  php spark reach:work --queue blog,publishing,community,default --limit 20');
            CLI::write('Then re-run this command; anything still listed did not get a cover.');

            return EXIT_SUCCESS;
        } catch (Throwable $e) {
            CLI::error('reach:blog-generate-covers failed: ' . $e->getMessage());

            return EXIT_ERROR;
        }
    }

    /**
     * Why cover generation cannot run right now, or null when it can.
     *
     * Queueing blocks that are certain to fail just moves the failure and
     * leaves work-block noise behind, so this is checked before writing.
     */
    private function generationBlockedReason(): ?string
    {
        if (! (new BlogFeatureFlags())->isEnabled('image_generation')) {
            return 'image generation is disabled (BLOG_IMAGE_GENERATION_ENABLED).';
        }

        try {
            $registry   = new ImageProviderRegistry();
            $configured = [];
            foreach ($registry->allKeys() as $key) {
                if ($registry->resolve($key)->isConfigured()) {
                    $configured[] = $key;
                }
            }

            if ($configured === []) {
                return 'no image provider is configured.';
            }
        } catch (Throwable $e) {
            return 'the image provider registry could not be read: ' . $e->getMessage();
        }

        return null;
    }

    /**
     * Blog items past approval whose publication profile has no featured image.
     *
     * @return list<array<string, mixed>>
     */
    private function itemsMissingCovers($db, int $limit): array
    {
        $rows = $db->table('reach_content_items')
            ->select('id, title, workflow_status, current_version_id')
            ->where('content_type', 'blog')
            ->where('deleted_at IS NULL', null, false)
            ->whereIn('workflow_status', self::PUBLISHABLE_STATES)
            ->orderBy('id', 'ASC')
            ->get()
            ->getResultArray();

        $out = [];
        foreach ($rows as $row) {
            $id = (int) $row['id'];

            $profile = $db->table('reach_blog_publication_profiles')
                ->where('content_item_id', $id)->get()->getRowArray();

            // No profile at all counts as no cover — reach:blog-fix-readiness
            // creates the profile, this fills the image it cannot derive.
            if ($profile && trim((string) ($profile['featured_image_reference'] ?? '')) !== '') {
                continue;
            }

            // CoverSweepService re-queues cover work for *parked* articles
            // under its own daily key, so an item in both populations would
            // otherwise get two GENERATE_IMAGE blocks and be billed for two
            // images. Skip anything that already has cover work in flight,
            // whichever key created it.
            $inFlight = $db->table('reach_work_blocks')
                ->where('content_item_id', $id)
                ->where('block_type', 'GENERATE_IMAGE')
                ->whereIn('eligibility_status', ['pending', 'eligible', 'queued', 'running'])
                ->countAllResults() > 0;

            if ($inFlight) {
                continue;
            }

            $out[] = [
                'id'                 => $id,
                'title'              => (string) $row['title'],
                'workflow_status'    => (string) $row['workflow_status'],
                'content_version_id' => (int) ($row['current_version_id'] ?? 0),
            ];

            if ($limit > 0 && count($out) >= $limit) {
                break;
            }
        }

        return $out;
    }
}
